@Host = http://localhost:5175

GET {{Host}}/shorten?url=https://animationflow.hr
###

GET {{Host}}/shorten?url=http://youtube.com
###

GET {{Host}}/shorten
###

GET {{Host}}/shorten?url
###

GET {{Host}}/shorten?url=animationflow
###

GET {{Host}}/shorten?url=animationflow.hr
###
